apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: service-registry-server
spec:
  selector:
    matchLabels:
      app: service-registry-server
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service-registry-server
    spec:
      containers:
        - name: service-registry-server
          image: localhost:5000/service-registry-server
          ports:
            - containerPort: 8761
---
kind: Service
apiVersion: v1
metadata:
  name: service-registry-server
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: service-registry-server
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
---
kind: Service
apiVersion: v1
metadata:
  name: zipkin
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: zipkin